apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-deployment-dev
  namespace: devops-project-dev
  labels:
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
        environment: development
    spec:
      containers:
      - name: webapi
        image: webapi:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: webapi-service-dev
  namespace: devops-project-dev
  labels:
    environment: development
spec:
  selector:
    app: webapi
    environment: development
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30001
  type: NodePort
