serverFiles:
  alertmanager.yml:
    global:
      smtp_smarthost: '***'
      smtp_from: '***'
      smtp_auth_username: '***'
      smtp_auth_password: '***'
      smtp_hello: 'smtp.gmail.com'
      smtp_require_tls: true
    route:
      receiver: 'email-alert'
      group_by: ['PodIsUp']
    receivers:
      - name: 'email-alert'
        email_configs:
          - to: 'lazhar.hamel@efrei.fr'
            send_resolved: true
            headers:
              Subject: 'Prometheus alert'
            text: |
              Alert: {{ .CommonLabels.alertname }}
              Severity: {{ .CommonLabels.severity }}
              Description: {{ .CommonAnnotations.description }}

